### ISSUE TITLE
install and enable acpi for VM types other than xen pv

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/addon-context-alpine#6]
We should probably by default install acpi and enable it, unless we're in a xen pv domU.
(Or just disable it on first boot if /proc/xen is present)

For anything else, OpenNebula doesn't know how to shut it down (not exposed by hypervisor & no event channel)
It seems by default, without acpi(d) alpine won't do a shut down action on power button press.

Could someone confirm?

**Comment by vholer** [comment]
Closing this issue here, reopened inside the main Linux contextualization repo:
https://github.com/OpenNebula/addon-context-linux/issues/97

This repo is now considered as obsolete:
https://opennebula.org/new-linux-contextualization-packages/
